import pandas as pd
import matplotlib.pyplot as plt
df = pd.read_csv('survey.csv')
print("Data Preview:")
print(df.head())
satisfaction_counts = df['Satisfaction'].value_counts()
print("\nSatisfaction Counts:")
print(satisfaction_counts)
plt.figure(figsize=(8, 5))
plt.bar(satisfaction_counts.index, satisfaction_counts.values, color='skyblue')
plt.xlabel("Satisfaction Level")
plt.ylabel("Number of Responses")
plt.title("User Satisfaction Survey Results")
plt.xticks(rotation=45)
plt.show()
